//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignSubject
    {
        public int a_id { get; set; }
        public string a_subjectID { get; set; }
        public string a_classID { get; set; }
        public string a_semester { get; set; }
        public string a_instructorID { get; set; }
    }
}
