//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class assign_Instructor
    {
        public int ai_ID { get; set; }
        public string ai_semester { get; set; }
        public string ai_classID { get; set; }
        public string ai_subjectID { get; set; }
        public string ai_instructorID { get; set; }
    }
}
