//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_S
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string YearLevel { get; set; }
        public string DepartmentID { get; set; }
        public string CourseID { get; set; }
    }
}
