//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int InstructorID { get; set; }
        public string Instructor_fname { get; set; }
        public string Instructor_mname { get; set; }
        public string Instructor_lname { get; set; }
        public string Department_ID { get; set; }
    }
}
