//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class regisGrade
    {
        public int regis_ID { get; set; }
        public string SP_ID { get; set; }
        public string studentID { get; set; }
        public string schoolID { get; set; }
        public string classID { get; set; }
        public string grade { get; set; }
    }
}
