//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentBackground
    {
        public int StudentID { get; set; }
        public string S_fname { get; set; }
        public string S_mname { get; set; }
        public string S_lname { get; set; }
        public string S_Sex { get; set; }
        public string S_Birthdate { get; set; }
        public string S_mNumber { get; set; }
        public string S_emailAdd { get; set; }
        public string S_Religion { get; set; }
        public string S_Citizenship { get; set; }
        public string S_Province { get; set; }
        public string S_municipality { get; set; }
        public string S_barangay { get; set; }
        public string S_Guardian_fname { get; set; }
        public string S_Guardian_lname { get; set; }
        public string S_Guardian_mname { get; set; }
        public string S_Guardian_contact { get; set; }
    }
}
