//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Profile
    {
        public int SP_ID { get; set; }
        public string StudentID { get; set; }
        public string DepartmentID { get; set; }
        public string CourseID { get; set; }
        public string YearLevel { get; set; }
        public string ClassID { get; set; }
        public string Semester { get; set; }
        public string SubjectID { get; set; }
        public string InstructorID { get; set; }
        public string Grade { get; set; }
        public string SchoolID { get; set; }
        public string status { get; set; }
    }
}
