//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionGrade
    {
        public int tran_ID { get; set; }
        public string classID { get; set; }
        public string subjectID { get; set; }
        public string instructorID { get; set; }
        public string feedback_Instructor { get; set; }
        public string status_Instructor { get; set; }
        public string status_Dean { get; set; }
        public string feedback_Dean { get; set; }
        public string status_Registrar { get; set; }
        public string feedback_Registrar { get; set; }
        public string a_ID { get; set; }
    }
}
