//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertypeLogin
    {
        public int accountID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
        public string userID { get; set; }
    }
}
